import { Amiri, Lateef } from "next/font/google";
import "./globals.css";
import { SettingsProvider } from "@/context/SettingsContext";

const amiri = Amiri({ subsets: ["arabic"], weight: ["400", "700"], variable: "--font-amiri" });
const lateef = Lateef({ subsets: ["arabic"], weight: ["400", "700"], variable: "--font-lateef" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${amiri.variable} ${lateef.variable} `}
    >
      <body suppressHydrationWarning={true}>
        <SettingsProvider>
          {children}
        </SettingsProvider>
      </body>
    </html>
  );
}
